name: taskmanager
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+5

environment:
  sdk: 3.7.2


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

  # Core packages for the refactor
  get: ^4.7.2
  get_storage: ^2.1.1 # Local storage solution
  flutter_screenutil: ^5.9.3 # Responsive UI toolkit
  uuid: ^4.5.1 # For generating unique task IDs
  flutter_local_notifications: ^19.0.0
  flutter_timezone: ^4.1.0 # For timezone-aware scheduled notifications
  #flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
